### ISSUE TITLE
Applestore submit error

### ISSUE THREAD

**Issue by hsmith825** [jcesarmobile/iSpeechPlugin#3]
I get the following error when I submit to the Apple store:  iSpeechSDK.bundle” does not contain a bundle excutable.  Error ITMS-90535.

Help!

**Comment by jcesarmobile** [comment]
I've updated iSpeech SDK, not sure if they have fixed that problem. Can you test it and let me know if it's fixed?

**Comment by jcesarmobile** [comment]
I've updated iSpeech SDK, not sure if they have fixed that problem. Can you test it and let me know if it's fixed?

**Comment by jcesarmobile** [comment]
I've updated iSpeech SDK, not sure if they have fixed that problem. Can you test it and let me know if it's fixed?

**Comment by jcesarmobile** [comment]
I've updated iSpeech SDK, not sure if they have fixed that problem. Can you test it and let me know if it's fixed?

**Comment by hsmith825** [comment]
Hi Julio,

 

The problem is not fixed.  There is a simple work around.  Remove the CFBundleExecutable key from the iSpeech Info.plist.

 

Thanks!

Howard

**Comment by jcesarmobile** [comment]
iSpeech is a 3rd party library, not my own, I have no access to the info.plist, it's compiled inside libiSpeechSDK.a.
Did you uninstall and reinstall the plugin? I updated another plugin that uses iSpeech SDK and one user told me that it was fixed.

**Comment by hsmith825** [comment]
I know but this is an apple issue.  It is a simple work around until apple changes it.  But that is your decision.

 

Thanks!

**Comment by jcesarmobile** [comment]
I've removed the CFBundleExecutable key, let me know if it fixes the issue
